// tailwind.config.ts
import type { Config } from "tailwindcss";

const config = {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        // Brand Colors - Amber/Gold for premium feel
        brand: {
          DEFAULT: "hsl(var(--brand))",
          50: "hsl(var(--brand-50))",
          100: "hsl(var(--brand-100))",
          200: "hsl(var(--brand-200))",
          300: "hsl(var(--brand-300))",
          400: "hsl(var(--brand-400))",
          500: "hsl(var(--brand-500))",
          600: "hsl(var(--brand-600))",
          700: "hsl(var(--brand-700))",
          800: "hsl(var(--brand-800))",
          900: "hsl(var(--brand-900))",
          foreground: "hsl(var(--brand-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          50: "hsl(239 84% 97%)",
          100: "hsl(239 84% 94%)",
          200: "hsl(239 84% 88%)",
          300: "hsl(239 84% 80%)",
          400: "hsl(239 84% 72%)",
          500: "hsl(239 84% 67%)",
          600: "hsl(239 84% 60%)",
          700: "hsl(239 84% 52%)",
          800: "hsl(239 84% 45%)",
          900: "hsl(239 84% 38%)",
          foreground: "hsl(var(--primary-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          50: "hsl(160 84% 97%)",
          100: "hsl(160 84% 90%)",
          200: "hsl(160 84% 80%)",
          300: "hsl(160 84% 65%)",
          400: "hsl(160 84% 50%)",
          500: "hsl(160 84% 42%)",
          600: "hsl(160 84% 39%)",
          700: "hsl(160 84% 32%)",
          800: "hsl(160 84% 25%)",
          900: "hsl(160 84% 18%)",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          50: "hsl(38 92% 97%)",
          100: "hsl(38 92% 90%)",
          200: "hsl(38 92% 80%)",
          300: "hsl(38 92% 65%)",
          400: "hsl(38 92% 55%)",
          500: "hsl(38 92% 50%)",
          600: "hsl(38 92% 42%)",
          700: "hsl(38 92% 35%)",
          800: "hsl(38 92% 28%)",
          900: "hsl(38 92% 20%)",
          foreground: "hsl(var(--warning-foreground))",
        },
        error: {
          DEFAULT: "hsl(var(--destructive))",
          50: "hsl(0 84% 97%)",
          100: "hsl(0 84% 92%)",
          200: "hsl(0 84% 85%)",
          300: "hsl(0 84% 75%)",
          400: "hsl(0 84% 65%)",
          500: "hsl(0 84% 60%)",
          600: "hsl(0 84% 52%)",
          700: "hsl(0 84% 45%)",
          800: "hsl(0 84% 38%)",
          900: "hsl(0 84% 30%)",
          foreground: "hsl(var(--destructive-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          50: "hsl(239 84% 97%)",
          100: "hsl(239 84% 94%)",
          200: "hsl(239 84% 88%)",
          300: "hsl(239 84% 80%)",
          400: "hsl(239 84% 72%)",
          500: "hsl(239 84% 67%)",
          600: "hsl(239 84% 60%)",
          700: "hsl(239 84% 52%)",
          800: "hsl(239 84% 45%)",
          900: "hsl(239 84% 38%)",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "fade-out": {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        "slide-in-from-top": {
          from: { transform: "translateY(-10px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        "slide-in-from-bottom": {
          from: { transform: "translateY(10px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        "slide-in-from-left": {
          from: { transform: "translateX(-10px)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
        "slide-in-from-right": {
          from: { transform: "translateX(10px)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
        "pulse-subtle": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.8" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "fade-out": "fade-out 0.3s ease-out",
        "slide-in-from-top": "slide-in-from-top 0.3s ease-out",
        "slide-in-from-bottom": "slide-in-from-bottom 0.3s ease-out",
        "slide-in-from-left": "slide-in-from-left 0.3s ease-out",
        "slide-in-from-right": "slide-in-from-right 0.3s ease-out",
        "pulse-subtle": "pulse-subtle 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      fontFamily: {
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
      },
      boxShadow: {
        soft: "0 2px 8px rgba(0, 0, 0, 0.04)",
        "soft-lg": "0 4px 16px rgba(0, 0, 0, 0.06)",
        "soft-xl": "0 8px 24px rgba(0, 0, 0, 0.08)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;

export default config;
